import { type AppType } from "next/dist/shared/lib/utils";
import Head from "next/head";
import Header from "~/components/Header";
import ProductsProvider from "~/providers/ProductsProvider";
import StoreStatusProvider from "~/providers/StoreStatusProvider";

import "~/styles/globals.css";

const MyApp: AppType = ({ Component, pageProps }) => {
  return (
    <StoreStatusProvider>
      <ProductsProvider>
        <>
          <Head>
            <title>Pineapple store</title>
            <meta name="description" content="Generated by create-t3-app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <Header />
        </>
        <Component {...pageProps} />
      </ProductsProvider>
    </StoreStatusProvider>
  );
};

export default MyApp;
