import { ClerkProvider } from "@clerk/nextjs";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { type AppType } from "next/dist/shared/lib/utils";
import Head from "next/head";
import Header from "~/components/Header";
// import ProductsProvider from "~/providers/ProductsProvider";
// import StoreProvider from "~/providers/StoreProvider";
import StoreStatusProvider from "~/providers/StoreStatusProvider";
import { UserProvider } from "~/providers/UserProvider";

import "~/styles/globals.css";

const MyApp: AppType = ({ Component, pageProps }) => {
  const queryClient = new QueryClient();

  return (
    <ClerkProvider>
      {/* <UserProvider> */}
        {/* <QueryClientProvider client={queryClient}> */}
          {/* <StoreProvider> */}
            {/* <StoreStatusProvider> */}
              {/* <ProductsProvider> */}
                <>
                  <Head>
                    <title>Pineapple store</title>
                    <meta
                      name="description"
                      content="Generated by create-t3-app"
                    />
                    <link rel="icon" href="/favicon.ico" />
                  </Head>
                  <Header />
                </>
                <Component {...pageProps} />
              {/* </ProductsProvider> */}
            {/* </StoreStatusProvider> */}
          {/* </StoreProvider> */}
        {/* </QueryClientProvider> */}
      {/* </UserProvider> */}
    </ClerkProvider>
  );
};

export default MyApp;
